apiVersion: v1
kind: ConfigMap
metadata:
  name: message-reader-service-config
data:
  PORT: "50051"
  MESSAGE_PAGE_SIZE: "20"
  MONGO_ADDR: "mongo-service.mongodb.svc.cluster.local:27017"
  MONGO_USER: "root"
  MONGO_TIMEOUT: "10s"
  MONGO_DB_NAME: "darda_chat"
  MONGO_COLLECTION_NAME: "messages"
  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"
