apiVersion: v1
kind: Service
metadata:
  name: message-reader-service
spec:
  selector:
    app: message-reader-service
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  type: ClusterIP