apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
data:
  PORT: "8080"
  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"
  SUBS_CHAN_BUFFER_SIZE: "30"
  AMQP_USER: "devuser"
  AMQP_HOST: "rabbitmq-service.rabbitmq.svc.cluster.local:5672"
  MESSAGE_READER_SERVICE_ADDR: "message-reader-service:50051"
