apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox:1.36
        env:
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: chat-service-config
              key: REDIS_ADDR
        command:
          - sh
          - -c
          - |
            until nc -z "$REDIS_ADDR" 6379; do
              echo "Waiting for Redis to accept connections..."
              sleep 2
            done
            echo "Redis is up!"
      containers:
      - name: chat-service
        image: nsmsb/chat-service:v0.0.1
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: chat-service-config
              key: REDIS_ADDR
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: chat-service-config
              key: REDIS_DB
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: chat-service-secret
              key: redis-password
        - name: SUBS_CHAN_BUFFER_SIZE
          valueFrom:
            configMapKeyRef:
              name: chat-service-config
              key: SUBS_CHAN_BUFFER_SIZE
