apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-writer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-writer-service
  template:
    metadata:
      labels:
        app: message-writer-service
    spec:
      containers:
      - name: message-writer-service
        image: nsmsb/message-writer-service:v0.0.1
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: CONSUMER_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: message-writer-service-config
              key: CONSUMER_POOL_SIZE
        - name: AMQP_USER
          valueFrom:
            configMapKeyRef:
              name: message-writer-service-config
              key: AMQP_USER
        - name: AMQP_PASS
          valueFrom:
            secretKeyRef:
              name: message-writer-service-secret
              key: amqp-password
        - name: AMQP_HOST
          valueFrom:
            configMapKeyRef:
              name: message-writer-service-config
              key: AMQP_HOST
        - name: MONGO_ADDR
          valueFrom:
            configMapKeyRef:
              name: message-writer-service-config
              key: MONGO_ADDR
        - name: MONGO_USER
          valueFrom:
            configMapKeyRef:
              name: message-writer-service-config
              key: MONGO_USER
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: message-writer-service-secret
              key: mongo-password
        - name: MONGO_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: message-writer-service-config
              key: MONGO_TIMEOUT
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: message-writer-service-config
              key: MONGO_DB_NAME
        - name: MONGO_COLLECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: message-writer-service-config
              key: MONGO_COLLECTION_NAME
