apiVersion: v1
kind: Secret
metadata:
  name: message-writer-service-secret
type: Opaque
data:
  amqp-password: UGFzczEyMzQ=  # base64 encoded 'Pass1234'
  mongo-password: UGFzczEyMzQ=  # base64 encoded 'Pass1234'
  redis-password: UGFzczEyMzQ=  # base64 encoded 'Pass1234'


